name: ncl_pos
description: "A new Flutter project."
publish_to: 'none' # This line prevents publishing to pub.dev.

version: 0.0.1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0  
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  firebase_auth: ^5.3.1
  iconly: ^1.0.1

  user_repository:
    path: packages/user_repository  # Use a relative path for portability

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/
