// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIsE0lQ_V-DbKlYdAKECdQCn0f4JcegBw',
    appId: '1:709522347058:web:e061f741b2700294df582b',
    messagingSenderId: '709522347058',
    projectId: 'ncl-pos-ruwas3',
    authDomain: 'ncl-pos-ruwas3.firebaseapp.com',
    storageBucket: 'ncl-pos-ruwas3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTe-J5Ni5JLHgn-ogLYOo2Oerx7SKGJug',
    appId: '1:709522347058:android:c3cf3e3e34a99af6df582b',
    messagingSenderId: '709522347058',
    projectId: 'ncl-pos-ruwas3',
    storageBucket: 'ncl-pos-ruwas3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYFBywyurDYcMapNCjwQjYTB4WidNbCJQ',
    appId: '1:709522347058:ios:5264a36de1977e6bdf582b',
    messagingSenderId: '709522347058',
    projectId: 'ncl-pos-ruwas3',
    storageBucket: 'ncl-pos-ruwas3.appspot.com',
    iosBundleId: 'com.example.nclPos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYFBywyurDYcMapNCjwQjYTB4WidNbCJQ',
    appId: '1:709522347058:ios:5264a36de1977e6bdf582b',
    messagingSenderId: '709522347058',
    projectId: 'ncl-pos-ruwas3',
    storageBucket: 'ncl-pos-ruwas3.appspot.com',
    iosBundleId: 'com.example.nclPos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIsE0lQ_V-DbKlYdAKECdQCn0f4JcegBw',
    appId: '1:709522347058:web:b0a4a73ac8fab756df582b',
    messagingSenderId: '709522347058',
    projectId: 'ncl-pos-ruwas3',
    authDomain: 'ncl-pos-ruwas3.firebaseapp.com',
    storageBucket: 'ncl-pos-ruwas3.appspot.com',
  );

}